[2023-06-12T18:06:30.848+0700] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: ETL_psql_redshift_dag.Load_to_psql scheduled__2023-06-11T00:00:00+00:00 [queued]>
[2023-06-12T18:06:30.889+0700] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: ETL_psql_redshift_dag.Load_to_psql scheduled__2023-06-11T00:00:00+00:00 [queued]>
[2023-06-12T18:06:30.890+0700] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-06-12T18:06:30.890+0700] {taskinstance.py:1280} INFO - Starting attempt 1 of 3
[2023-06-12T18:06:30.890+0700] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-06-12T18:06:30.915+0700] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): Load_to_psql> on 2023-06-11 00:00:00+00:00
[2023-06-12T18:06:30.921+0700] {standard_task_runner.py:55} INFO - Started process 13896 to run task
[2023-06-12T18:06:30.926+0700] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'ETL_psql_redshift_dag', 'Load_to_psql', 'scheduled__2023-06-11T00:00:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/dags_setup.py', '--cfg-path', '/var/folders/13/nw165ws91y30x7r8_6b34m_m0000gn/T/tmptwv6q4xs']
[2023-06-12T18:06:30.928+0700] {standard_task_runner.py:83} INFO - Job 34: Subtask Load_to_psql
[2023-06-12T18:06:31.106+0700] {task_command.py:388} INFO - Running <TaskInstance: ETL_psql_redshift_dag.Load_to_psql scheduled__2023-06-11T00:00:00+00:00 [running]> on host vus-macbook-pro.local
[2023-06-12T18:06:31.145+0700] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=vupham
AIRFLOW_CTX_DAG_ID=ETL_psql_redshift_dag
AIRFLOW_CTX_TASK_ID=Load_to_psql
AIRFLOW_CTX_EXECUTION_DATE=2023-06-11T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-11T00:00:00+00:00
[2023-06-12T18:06:31.199+0700] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/opt/homebrew/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/vupham/Desktop/DE_Project/dags/ETL_psql/Load/Load_psql.py", line 53, in Load_schema
    Load_table(f"Sale_schema.{table}", df, cur);
  File "/Users/vupham/Desktop/DE_Project/dags/ETL_psql/Load/Load_psql.py", line 23, in Load_table
    cur.executemany(query, records);
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "locations_pkey"
DETAIL:  Key (postal_code)=(39980) already exists.

[2023-06-12T18:06:31.207+0700] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_psql_redshift_dag, task_id=Load_to_psql, execution_date=20230611T000000, start_date=20230612T110630, end_date=20230612T110631
[2023-06-12T18:06:31.213+0700] {standard_task_runner.py:100} ERROR - Failed to execute job 34 for task Load_to_psql (duplicate key value violates unique constraint "locations_pkey"
DETAIL:  Key (postal_code)=(39980) already exists.
; 13896)
[2023-06-12T18:06:31.253+0700] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-06-12T18:06:31.269+0700] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-12T18:20:35.836+0700] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: ETL_psql_redshift_dag.Load_to_psql scheduled__2023-06-11T00:00:00+00:00 [queued]>
[2023-06-12T18:20:35.841+0700] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: ETL_psql_redshift_dag.Load_to_psql scheduled__2023-06-11T00:00:00+00:00 [queued]>
[2023-06-12T18:20:35.841+0700] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-06-12T18:20:35.841+0700] {taskinstance.py:1280} INFO - Starting attempt 1 of 3
[2023-06-12T18:20:35.841+0700] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-06-12T18:20:35.848+0700] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): Load_to_psql> on 2023-06-11 00:00:00+00:00
[2023-06-12T18:20:35.850+0700] {standard_task_runner.py:55} INFO - Started process 16481 to run task
[2023-06-12T18:20:35.853+0700] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'ETL_psql_redshift_dag', 'Load_to_psql', 'scheduled__2023-06-11T00:00:00+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/dags_setup.py', '--cfg-path', '/var/folders/13/nw165ws91y30x7r8_6b34m_m0000gn/T/tmpjdxerbx3']
[2023-06-12T18:20:35.854+0700] {standard_task_runner.py:83} INFO - Job 62: Subtask Load_to_psql
[2023-06-12T18:20:35.902+0700] {task_command.py:388} INFO - Running <TaskInstance: ETL_psql_redshift_dag.Load_to_psql scheduled__2023-06-11T00:00:00+00:00 [running]> on host vus-macbook-pro.local
[2023-06-12T18:20:35.948+0700] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=vupham
AIRFLOW_CTX_DAG_ID=ETL_psql_redshift_dag
AIRFLOW_CTX_TASK_ID=Load_to_psql
AIRFLOW_CTX_EXECUTION_DATE=2023-06-11T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-11T00:00:00+00:00
[2023-06-12T18:20:46.563+0700] {logging_mixin.py:137} INFO - Successfully insert data to table Sale_schema.locations
[2023-06-12T18:21:01.890+0700] {logging_mixin.py:137} INFO - Successfully insert data to table Sale_schema.customers
[2023-06-12T18:22:29.005+0700] {logging_mixin.py:137} INFO - Successfully insert data to table Sale_schema.products
[2023-06-12T18:23:24.358+0700] {logging_mixin.py:137} INFO - Successfully insert data to table Sale_schema.sales
[2023-06-12T18:24:17.417+0700] {logging_mixin.py:137} INFO - Successfully insert data to table Sale_schema.shipments
[2023-06-12T18:24:17.505+0700] {python.py:177} INFO - Done. Returned value was: None
[2023-06-12T18:24:17.510+0700] {taskinstance.py:1318} INFO - Marking task as SUCCESS. dag_id=ETL_psql_redshift_dag, task_id=Load_to_psql, execution_date=20230611T000000, start_date=20230612T112035, end_date=20230612T112417
[2023-06-12T18:24:17.551+0700] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-06-12T18:24:17.578+0700] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
